### ISSUE TITLE
Setup kanban board

### ISSUE THREAD

**Issue by Mithi-code** [Mithi-code/Space-travelers-hub#18]
### [project url](https://github.com/Mithi-code/Space-travelers-hub/projects/1)
We are 2 people.
Student A - @Mithi-code 
Student B - @youmari

**Comment by TedLivist** [comment]
## STATUS: APPROVED ✔️ ✔️

Hi @Mithi-code and @youmari,

Your Kanban columns are well set up and your cards complete and assigned :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the issue thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
